### ISSUE TITLE
iOS: Back button barely visible

### ISSUE THREAD

**Issue by dharzheim** [urbanairship/capacitor-airship#10] opened 2024-05-30 12:59 UTC
# Preliminary Info

### What Airship dependencies are you using?
Capacitor Plugin 1.2.2

### What are the versions of any relevant development tools you are using?
Xcode 15.3

# Report

### What unexpected behavior are you seeing?
Back button in preference center is barely visible

### What is the expected behavior?
Clearly visible back button

### What are the steps to reproduce the unexpected behavior?
Open preference center on iOS device

### Do you have logging for the issue?
-

![image](https://github.com/urbanairship/capacitor-airship/assets/21546281/9661132a-a013-4070-9cce-a56ab355af4a)

Older version:
![image](https://github.com/urbanairship/capacitor-airship/assets/21546281/3285df5a-17d6-4641-a157-87ba1e6c96ca)

**Comment by rlepinski** [comment] 2024-05-30 16:23
Are you setting a theme for that screen?

**Comment by crow** [comment] 2024-05-30 23:04
@dharzheim Looks like we found the issue, we'll get a patch out with a fix. Thanks for reporting.

**Comment by rlepinski** [comment] 2024-06-20 23:56
Fixed in 1.2.3

**Closed by rlepinski** 2024-06-20 23:56 UTC

**Comment by rlepinski** [comment] 2024-06-21 23:03
Had a regression in 1.2.3, if you update make sure to go to 1.2.4
